name: Deploy to Server

on:
  push:
    branches:
      - main  # O el branch en el que trabajas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Asegúrate de agregar tu clave SSH privada en GitHub Secrets

    - name: Deploy to server
      run: |
        ssh user@your-domain.com "cd /path/to/your/app && git pull && composer install && php artisan migrate"

