name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Ajusta la versión de PHP que estás usando
        extensions: mbstring, bcmath, xml  # Agrega las extensiones que necesites

    # Paso 3: Instalar Composer
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    # Paso 4: Instalar dependencias de Composer
    - name: Install dependencies
      run: composer install

    # Paso 5: Ejecutar PHPUnit
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --configuration phpunit.xml

    # Paso 6: Subir los resultados de PHPUnit como un artefacto
    - name: Upload PHPUnit Test Results
      uses: actions/upload-artifact@v2
      with:
        name: phpunit-results
        path: tests/_output
