name: PHP Composer

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - uses: actions/checkout@v4

    # Paso 2: Validar composer.json y composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Paso 3: Cache Composer packages
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Paso 4: Instalar dependencias
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    # Paso 5: Ejecutar pruebas de PHPUnit
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    # Optional: If you have tests, you can uncomment this step.
    # - name: Run test suite
    #   run: composer run-script test

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
