name: Build PHP Application

on:
  push:
    branches:
      - main  # O cualquier rama que quieras monitorear
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar PHP (instalar PHP y Composer)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Cambia la versión de PHP si es necesario

    # Paso 3: Instalar las dependencias con Composer
    - name: Install dependencies with Composer
      run: composer install --no-interaction

    # Paso 4: (Opcional) Generar el build si tienes scripts específicos para ello
    - name: Build application (optional)
      run: |
        # Si tienes un script de build en composer.json
        composer run build || echo "No build script defined"
